### 一 数据分析

#### 1. 查看数据类型

In [14]:
import pandas
data = pandas.read_csv("data.csv",encoding='gbk')
data.describe()

,Unnamed: 0,custid,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
count,4754.000000,4.754000e+03,4752.000000,4752.000000,4754.000000,4751.000000,4752.000000,4752.000000,4752.000000,4746.000000,...,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4450.000000,4457.000000
mean,6008.414178,1.690993e+06,0.021806,0.901294,1940.197728,14.160674,0.804411,0.365425,17.502946,29.029920,...,3390.038142,1820.357864,9187.009199,76.042630,4.732331,5.227507,16153.690823,8007.696881,24.112809,55.181512
std,3452.071428,1.034235e+06,0.041527,0.144856,3923.971494,694.180473,0.196920,0.170196,4.475616,22.722432,...,1474.206546,583.418291,7371.257043,14.536819,2.974596,3.409292,14301.037628,5679.418585,37.725724,53.486408
min,5.000000,1.140000e+02,0.000000,0.000000,0.000000,0.000000,0.120000,0.033000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,-2.000000
25%,3106.000000,7.593358e+05,0.010000,0.880000,0.000000,0.615000,0.670000,0.233000,15.000000,16.000000,...,2300.000000,1535.000000,4800.000000,77.000000,2.000000,3.000000,7800.000000,4737.000000,5.000000,10.000000
50%,6006.500000,1.634942e+06,0.010000,0.960000,500.000000,0.970000,0.860000,0.350000,17.000000,23.000000,...,3100.000000,1810.000000,7700.000000,79.000000,4.000000,5.000000,13800.000000,7050.000000,14.000000,36.000000
75%,8999.000000,2.597905e+06,0.020000,0.990000,2000.000000,1.600000,1.000000,0.480000,20.000000,32.000000,...,4300.000000,2100.000000,11700.000000,80.000000,7.000000,7.000000,20400.000000,10000.000000,24.000000,91.000000
max,11992.000000,4.004694e+06,1.000000,1.000000,68000.000000,47596.740000,1.000000,0.941000,42.000000,285.000000,...,10000.000000,6900.000000,87100.000000,87.000000,18.000000,20.000000,266400.000000,82800.000000,360.000000,323.000000

#### 2 查看每个特征列的类型

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4754 entries, 0 to 4753
Data columns (total 90 columns):
Unnamed: 0                                    4754 non-null int64
custid                                        4754 non-null int64
trade_no                                      4754 non-null object
bank_card_no                                  4754 non-null object
low_volume_percent                            4752 non-null float64
middle_volume_percent                         4752 non-null float64
take_amount_in_later_12_month_highest         4754 non-null int64
trans_amount_increase_rate_lately             4751 non-null float64
trans_activity_month                          4752 non-null float64
trans_activity_day                            4752 non-null float64
transd_mcc                                    4752 non-null float64
trans_days_interval_filter                    4746 non-null float64
trans_days_interval                           4752 non-null float64
regional_mobility                             4752 non-null float64
student_feature                               1756 non-null float64
repayment_capability                          4754 non-null int64
is_high_user                                  4754 non-null int64
number_of_trans_from_2011                     4752 non-null float64
first_transaction_time                        4752 non-null float64
historical_trans_amount                       4754 non-null int64
historical_trans_day                          4752 non-null float64
rank_trad_1_month                             4752 non-null float64
trans_amount_3_month                          4754 non-null int64
avg_consume_less_12_valid_month               4752 non-null float64
abs                                           4754 non-null int64
top_trans_count_last_1_month                  4752 non-null float64
avg_price_last_12_month                       4754 non-null int64
avg_price_top_last_12_valid_month             4650 non-null float64
reg_preference_for_trad                       4752 non-null object
trans_top_time_last_1_month                   4746 non-null float64
trans_top_time_last_6_month                   4746 non-null float64
consume_top_time_last_1_month                 4746 non-null float64
consume_top_time_last_6_month                 4746 non-null float64
cross_consume_count_last_1_month              4328 non-null float64
trans_fail_top_count_enum_last_1_month        4738 non-null float64
trans_fail_top_count_enum_last_6_month        4738 non-null float64
trans_fail_top_count_enum_last_12_month       4738 non-null float64
consume_mini_time_last_1_month                4728 non-null float64
max_cumulative_consume_later_1_month          4754 non-null int64
max_consume_count_later_6_month               4746 non-null float64
railway_consume_count_last_12_month           4742 non-null float64
pawns_auctions_trusts_consume_last_1_month    4754 non-null int64
pawns_auctions_trusts_consume_last_6_month    4754 non-null int64
jewelry_consume_count_last_6_month            4742 non-null float64
status                                        4754 non-null int64
source                                        4754 non-null object
first_transaction_day                         4752 non-null float64
trans_day_last_12_month                       4752 non-null float64
id_name                                       4478 non-null object
apply_score                                   4450 non-null float64
apply_credibility                             4450 non-null float64
query_org_count                               4450 non-null float64
query_finance_count                           4450 non-null float64
query_cash_count                              4450 non-null float64
query_sum_count                               4450 non-null float64
latest_query_time                             4450 non-null object
latest_one_month_apply                        4450 non-null float64
latest_three_month_apply                      4450 non-null float64
latest_six_month_apply                        4450 non-null float64
loans_score                                   4457 non-null float64
loans_credibility_behavior                    4457 non-null float64
loans_count                                   4457 non-null float64
loans_settle_count                            4457 non-null float64
loans_overdue_count                           4457 non-null float64
loans_org_count_behavior                      4457 non-null float64
consfin_org_count_behavior                    4457 non-null float64
loans_cash_count                              4457 non-null float64
latest_one_month_loan                         4457 non-null float64
latest_three_month_loan                       4457 non-null float64
latest_six_month_loan                         4457 non-null float64
history_suc_fee                               4457 non-null float64
history_fail_fee                              4457 non-null float64
latest_one_month_suc                          4457 non-null float64
latest_one_month_fail                         4457 non-null float64
loans_long_time                               4457 non-null float64
loans_latest_time                             4457 non-null object
loans_credit_limit                            4457 non-null float64
loans_credibility_limit                       4457 non-null float64
loans_org_count_current                       4457 non-null float64
loans_product_count                           4457 non-null float64
loans_max_limit                               4457 non-null float64
loans_avg_limit                               4457 non-null float64
consfin_credit_limit                          4457 non-null float64
consfin_credibility                           4457 non-null float64
consfin_org_count_current                     4457 non-null float64
consfin_product_count                         4457 non-null float64
consfin_max_limit                             4457 non-null float64
consfin_avg_limit                             4457 non-null float64
latest_query_day                              4450 non-null float64
loans_latest_day                              4457 non-null float64
dtypes: float64(70), int64(13), object(7)
memory usage: 3.3+ MB

#### 3 查看共有多少条数据

In [16]:
data.shape[0]

4754

#### 4 查看缺失值

In [17]:
data.isnull().sum().sort_values(ascending = False)

student_feature                               2998
cross_consume_count_last_1_month               426
apply_credibility                              304
query_cash_count                               304
latest_six_month_apply                         304
latest_three_month_apply                       304
latest_query_time                              304
query_sum_count                                304
latest_one_month_apply                         304
query_finance_count                            304
query_org_count                                304
apply_score                                    304
latest_query_day                               304
latest_one_month_loan                          297
loans_score                                    297
loans_credibility_behavior                     297
loans_count                                    297
loans_settle_count                             297
loans_overdue_count                            297
loans_org_count_behavior                       297
consfin_org_count_behavior                     297
loans_cash_count                               297
loans_latest_day                               297
latest_three_month_loan                        297
loans_product_count                            297
consfin_max_limit                              297
latest_six_month_loan                          297
consfin_product_count                          297
consfin_org_count_current                      297
consfin_credibility                            297
                                              ...
transd_mcc                                       2
trans_activity_day                               2
number_of_trans_from_2011                        2
first_transaction_time                           2
trans_activity_month                             2
historical_trans_day                             2
low_volume_percent                               2
avg_consume_less_12_valid_month                  2
top_trans_count_last_1_month                     2
middle_volume_percent                            2
trans_day_last_12_month                          2
reg_preference_for_trad                          2
first_transaction_day                            2
trans_days_interval                              2
bank_card_no                                     0
take_amount_in_later_12_month_highest            0
custid                                           0
trade_no                                         0
status                                           0
repayment_capability                             0
is_high_user                                     0
historical_trans_amount                          0
trans_amount_3_month                             0
abs                                              0
avg_price_last_12_month                          0
max_cumulative_consume_later_1_month             0
pawns_auctions_trusts_consume_last_1_month       0
pawns_auctions_trusts_consume_last_6_month       0
source                                           0
Unnamed: 0                                       0
Length: 90, dtype: int64

由以上可得，发现有 float int object 三种类型
特别注意的是Object 这一列
查找类型是object的这一列：

In [19]:
for i in range(90):
    if data.iloc[:,i].dtypes == "object":
        print(i)

2
3
28
45
48
55
75

把这几列单独展示

In [20]:
data_object = data.iloc[:,[2,3,28,45,48,55,75]]
data_object

,trade_no,bank_card_no,reg_preference_for_trad,source,id_name,latest_query_time,loans_latest_time
0,20180507115231274000000023057383,卡号1,一线城市,xs,蒋红,2018-04-25,2018-04-19
1,20180507121002192000000023073000,卡号1,一线城市,xs,崔向朝,2018-05-03,2018-05-05
2,20180507125159718000000023114911,卡号1,一线城市,xs,王中云,2018-05-05,2018-05-01
3,20180507121358683000000388283484,卡号1,三线城市,xs,何洋洋,2018-05-05,2018-05-03
4,20180507115448545000000388205844,卡号1,一线城市,xs,赵洋,2018-04-15,2018-01-07
5,20180507121233054000000388275132,卡号1,三线城市,xs,刘成,2018-05-04,2018-05-03
6,20180507121931540000000388298915,卡号1,一线城市,xs,周雨浓,2018-05-06,2018-05-04
7,20180507124659235000000023105807,卡号1,一线城市,xs,NaN,NaN,NaN
8,20180507115855621000000388224458,卡号1,三线城市,xs,周琰龙,2018-04-13,2018-04-30
9,20180504155156296000000021138084,卡号1,一线城市,xs,马晓辉,2018-04-16,2017-12-13
10,20180507123917136000000388381264,卡号1,一线城市,xs,冯子涵,2018-04-25,2018-04-28
11,20180507121556599000000023080022,卡号1,一线城市,xs,尚海,2018-04-06,2018-04-02
12,20180507114604230000000388176931,卡号1,三线城市,xs,何俊踊,2018-03-30,2018-05-01
13,20180507115807011000000388215609,卡号1,一线城市,xs,赵珊,2018-04-24,2018-04-28
14,20180507121351317000000388282601,卡号1,一线城市,xs,齐健,2018-04-21,2017-10-26
15,20180507120312643000000388240340,卡号1,一线城市,xs,覃杰脉,2018-05-03,2018-04-10
16,20180507115358209000000388203669,卡号1,境外,xs,周火文,2018-05-04,2018-05-06
17,20180507123013060000000388346445,卡号1,一线城市,xs,刘哲,2018-04-28,2018-04-30
18,20180507123317625000000388359399,卡号1,境外,xs,林森华,2018-04-11,2018-02-19
19,20180507122754609000000388339559,卡号1,一线城市,xs,王欢,2018-04-25,2018-03-31
20,20180507114736098000000388185623,卡号1,一线城市,xs,张霞,2018-05-04,2018-02-25
21,20180507122338228000000023086166,卡号1,一线城市,xs,徐翔,2018-04-30,2018-04-14
22,20180504181611848000000381832460,卡号1,境外,xs,陈鹏,2018-04-30,2018-05-03
23,20180507123855945000000388380951,卡号1,三线城市,xs,吴勤,2018-04-25,2018-04-28
24,20180507123355168000000388361170,卡号1,一线城市,xs,梁健,2018-04-23,2018-01-23
25,20180504162411113000000021172853,卡号1,境外,xs,张兵兵,2018-04-13,2018-02-11
26,20180507120445507000000388245413,卡号1,一线城市,xs,张奔驰,2018-04-27,2018-02-16
27,20180507123830326000000388380639,卡号1,三线城市,xs,段春红,2018-04-17,2018-05-01
28,20180507115610811000000388212340,卡号1,一线城市,xs,郑晓光,2018-05-02,2018-04-28
29,20180507123310399000000388357579,卡号1,一线城市,xs,谢志恒,NaN,2018-04-03
...,...,...,...,...,...,...,...
4724,20180507124934620000000388416059,卡号1,一线城市,xs,段宇佳,2018-04-16,2018-05-02
4725,20180507122940057000000388342910,卡号1,一线城市,xs,林峰华,2017-12-16,2018-01-27
4726,20180504162011976000000381367953,卡号1,境外,xs,赵发伟,2018-04-15,2018-03-12
4727,20180507114821935000000388187853,卡号1,一线城市,xs,何威,2018-04-09,2018-03-11
4728,20180507120905394000000023072119,卡号1,一线城市,xs,庞振宗,2018-04-19,2018-04-28
4729,20180507123942186000000388381507,卡号1,一线城市,xs,郭旭强,2018-05-04,2018-01-23
4730,20180507124818814000000388411045,卡号1,三线城市,xs,陈长城,2018-04-09,2017-12-30
4731,20180507123928918000000388381394,卡号1,三线城市,xs,罗森方,2018-05-05,2018-04-26
4732,20180507124249332000000388393507,卡号1,一线城市,xs,郑发春,2018-04-28,2017-08-30
4733,20180507114636248000000388181870,卡号1,二线城市,xs,孔迪俊,2018-04-23,2018-04-28
4734,20180507124936647000000388418873,卡号1,境外,xs,齐亚龙,2018-04-13,2017-12-27
4735,20180507121900401000000388295882,卡号1,一线城市,xs,魏欣旭,2018-05-05,2018-05-01
4736,20180507124233969000000023103541,卡号1,一线城市,xs,陈河根,2018-04-19,2017-12-02
4737,20180504170134092000000381539852,卡号1,一线城市,xs,黄彬彬,2018-05-03,2018-04-27
4738,20180507114726030000000023048892,卡号1,一线城市,xs,洪云飞,2018-03-20,2018-02-07
4739,20180504161419403000000381329175,卡号1,三线城市,xs,赵明,2018-04-22,2018-04-25
4740,20180507115324523000000388201054,卡号1,一线城市,xs,余孝意,2018-04-06,2017-11-25
4741,20180504183705135000000381895535,卡号1,一线城市,xs,潘培星,2018-04-25,2017-12-15
4742,20180507125018925000000023111153,卡号1,一线城市,xs,冯永,2018-05-03,2018-05-03
4743,20180504170654830000000381561522,卡号1,三线城市,xs,肖杰,2018-04-23,2018-04-22
4744,20180507115029481000000388194850,卡号1,一线城市,xs,李宇阳,2018-05-02,2018-02-08
4745,20180507123619864000000388369012,卡号1,三线城市,xs,孟祥彬,2018-05-06,2018-04-29
4746,20180507125012243000000023109396,卡号1,一线城市,xs,NaN,NaN,NaN
4747,20180507123811494000000388377504,卡号1,境外,xs,鄞佳旺,2018-05-06,2018-04-15
4748,20180507121025853000000388266701,卡号1,一线城市,xs,王成,2018-04-02,2018-03-14
4749,20180507120519228000000388247328,卡号1,一线城市,xs,王贤涛,2018-03-24,2018-03-10
4750,20180507114937914000000388192877,卡号1,一线城市,xs,胡晓歆宇,2018-04-20,2018-03-13
4751,20180507121340509000000388278785,卡号1,一线城市,xs,赵吉伟,2018-04-19,2018-03-13
4752,20180504161827128000000381357758,卡号1,一线城市,xs,罗松,2018-03-10,2018-04-18
4753,20180507124243041000000388391027,卡号1,一线城市,xs,李俊,2018-04-17,2018-03-14

可以看到，有两列"bank_card_no" 和 "source" 的数据每一行都是是完全一样的。这样都一样的数据是没有意义的
另外，因为要求的是预测一个用户是否会逾期，因此用户名字也是没用的，即 id_name 是没用的。trade_no 表示交易号，也是没用的
因此要在接下来处理中删掉

#### 5 查看每列某类重复值占的最大比例

In [21]:
import pandas as pd
# 计算每列出现频次最高的树占比
def similar(df):
    maxnum = (df.value_counts().max())/4754
    return maxnum
data_similar = pd.DataFrame(data.apply(similar),columns={"similar"})
# 根据频次降序排列
data_similar = data_similar.sort_values("similar",ascending=False)
print(data_similar)

                                             similar
source                                      1.000000
bank_card_no                                1.000000
jewelry_consume_count_last_6_month          0.989272
is_high_user                                0.988851
railway_consume_count_last_12_month         0.978334
status                                      0.749053
reg_preference_for_trad                     0.715818
cross_consume_count_last_1_month            0.645351
latest_one_month_fail                       0.621582
latest_one_month_loan                       0.495793
pawns_auctions_trusts_consume_last_1_month  0.490745
latest_one_month_suc                        0.482120
consume_mini_time_last_1_month              0.440682
regional_mobility                           0.410181
low_volume_percent                          0.383677
student_feature                             0.368952
trans_day_last_12_month                     0.367270
loans_overdue_count                         0.329828
take_amount_in_later_12_month_highest       0.329407
avg_consume_less_12_valid_month             0.310686
trans_fail_top_count_enum_last_1_month      0.294489
trans_activity_month                        0.290072
avg_price_top_last_12_valid_month           0.261043
top_trans_count_last_1_month                0.249895
latest_three_month_loan                     0.239167
consume_top_time_last_1_month               0.215187
loans_credibility_behavior                  0.204249
trans_fail_top_count_enum_last_6_month      0.199411
trans_top_time_last_1_month                 0.195204
middle_volume_percent                       0.194573
...                                              ...
trans_days_interval                         0.052377
number_of_trans_from_2011                   0.050273
trans_top_time_last_6_month                 0.049432
consume_top_time_last_6_month               0.047960
query_sum_count                             0.042070
trans_days_interval_filter                  0.039125
consfin_avg_limit                           0.031763
consfin_credit_limit                        0.031763
loans_latest_time                           0.028187
loans_latest_day                            0.027766
apply_score                                 0.025873
loans_settle_count                          0.024821
loans_count                                 0.021035
trans_amount_3_month                        0.020404
loans_avg_limit                             0.019562
loans_score                                 0.019142
history_suc_fee                             0.016828
avg_price_last_12_month                     0.015355
trans_amount_increase_rate_lately           0.010517
trans_activity_day                          0.008204
historical_trans_day                        0.006521
abs                                         0.003576
first_transaction_day                       0.002524
first_transaction_time                      0.002524
repayment_capability                        0.002103
historical_trans_amount                     0.001262
id_name                                     0.001052
custid                                      0.000210
trade_no                                    0.000210
Unnamed: 0                                  0.000210

[90 rows x 1 columns]

将占比超过 97%的特征视作为无关特征，在接下来的操作中将其删掉

### 二 无关特征删除

在“一 数据分析”中，找出了特征重复值占比超过 97% 的特征，将这些特征删除

In [22]:
data = data.drop(['Unnamed: 0',"bank_card_no","source","id_name","jewelry_consume_count_last_6_month","is_high_user",
"railway_consume_count_last_12_month","custid","trade_no"],axis=1)
data.head()

,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,0.01,0.99,0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,0.02,0.94,2000,1.28,1.00,0.458,19.0,30.0,14.0,4.0,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,0.04,0.96,0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,0.00,0.96,2000,0.13,0.57,0.777,22.0,14.0,6.0,3.0,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,0.01,0.99,0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

### 三 数据类型处理

无关特征删除后，还存有三个object类型特征，其中两列latest_query_time，loans_latest_time为时间数据，需要另外处理

对 reg_preference_for_trad 做独热编码

In [23]:
data = pd.get_dummies(data,columns=["reg_preference_for_trad"])
# 对于 get_dummies 使用说明见： https://blog.csdn.net/lujiandong1/article/details/52836051#commentBox

In [25]:
data = data.infer_objects()
# data['loans_latest_time'][2]
print(data.dtypes.value_counts())

float64    68
int64      10
uint8       5
object      2
dtype: int64

这里一列变成了5列

对于latest_query_time和loans_latest_time,先变为dtype: datetime64[ns]

In [26]:
data['latest_query_time'] = pd.to_datetime(data['latest_query_time'])
data['loans_latest_time'] = pd.to_datetime(data['loans_latest_time'])
B = [(data['loans_latest_time'][i]-data['loans_latest_time'][2]).days for i in range(4754)]
A = [(data['latest_query_time'][i]-data['latest_query_time'][2]).days for i in range(4754)]
C = [(data['latest_query_time'][i]-data['loans_latest_time'][2]).days for i in range(4754)]
query_time_minus = pd.DataFrame(A,columns =["query_minus"])
loans_time_minus = pd.DataFrame(B,columns =["loans_time"])
query_loans_time_minus = pd.DataFrame(C,columns =["query_loans_time"])
data = pd.concat([query_time_minus,loans_time_minus,query_loans_time_minus, data], axis=1)
data = data.drop(['latest_query_time','loans_latest_time'], axis=1)

选择基准时间data_obj[‘loans_latest_time’][2]，计算其他列时间数据，与它相距多少天，比方2018.7.20-2018.7.25,结果为-5天。

将列latest_query_time和loans_latest_time数据相减，得到一个相差多少天的数据。

### 4 缺失值填补

对于数值型数据，采用均值填充

In [27]:
data = data.fillna(data.mean())
data

,query_minus,loans_time,query_loans_time,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,...,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day,reg_preference_for_trad_一线城市,reg_preference_for_trad_三线城市,reg_preference_for_trad_二线城市,reg_preference_for_trad_其他城市,reg_preference_for_trad_境外
0,-10.000000,-12.000000,-6.000000,0.01,0.99,0,0.90,0.55,0.313,17.0,...,2.000000,1200.000000,1200.000000,12.000000,18.000000,1,0,0,0,0
1,-2.000000,4.000000,2.000000,0.02,0.94,2000,1.28,1.00,0.458,19.0,...,6.000000,22800.000000,9360.000000,4.000000,2.000000,1,0,0,0,0
2,0.000000,0.000000,4.000000,0.04,0.96,0,1.00,1.00,0.114,13.0,...,1.000000,4200.000000,4200.000000,2.000000,6.000000,1,0,0,0,0
3,0.000000,2.000000,4.000000,0.00,0.96,2000,0.13,0.57,0.777,22.0,...,5.000000,30000.000000,12180.000000,2.000000,4.000000,0,1,0,0,0
4,-20.000000,-114.000000,-16.000000,0.01,0.99,0,0.46,1.00,0.175,13.0,...,2.000000,8400.000000,8250.000000,22.000000,120.000000,1,0,0,0,0
5,-1.000000,2.000000,3.000000,0.02,0.98,2000,7.59,1.00,0.733,27.0,...,12.000000,20400.000000,8130.000000,3.000000,4.000000,0,1,0,0,0
6,1.000000,3.000000,5.000000,0.02,0.98,0,23.67,0.94,0.087,10.0,...,2.000000,16800.000000,8900.000000,1.000000,3.000000,1,0,0,0,0
7,-22.789663,-49.855957,-18.789663,0.02,0.98,0,0.25,0.88,0.302,19.0,...,5.227507,16153.690823,8007.696881,24.112809,55.181512,1,0,0,0,0
8,-22.000000,-1.000000,-18.000000,0.03,0.65,0,0.31,0.76,0.472,15.0,...,11.000000,19200.000000,7987.000000,24.000000,7.000000,0,1,0,0,0
9,-19.000000,-139.000000,-15.000000,0.01,0.99,500,0.80,1.00,0.088,15.0,...,0.000000,0.000000,0.000000,18.000000,142.000000,1,0,0,0,0
10,-10.000000,-3.000000,-6.000000,0.01,0.99,0,2.48,0.94,0.322,16.0,...,8.000000,20400.000000,7757.000000,12.000000,9.000000,1,0,0,0,0
11,-29.000000,-29.000000,-25.000000,0.01,0.99,500,0.72,0.63,0.450,17.0,...,3.000000,13200.000000,9400.000000,31.000000,35.000000,1,0,0,0,0
12,-36.000000,0.000000,-32.000000,0.00,0.73,5000,0.09,0.70,0.697,28.0,...,8.000000,42000.000000,16985.000000,38.000000,6.000000,0,1,0,0,0
13,-11.000000,-3.000000,-7.000000,0.01,0.79,0,1.24,1.00,0.447,16.0,...,7.000000,11400.000000,5460.000000,13.000000,9.000000,1,0,0,0,0
14,-14.000000,-187.000000,-10.000000,0.01,0.89,4000,0.07,1.00,0.233,17.0,...,0.000000,0.000000,0.000000,16.000000,193.000000,1,0,0,0,0
15,-2.000000,-21.000000,2.000000,0.01,0.99,0,1.13,0.76,0.480,20.0,...,11.000000,33600.000000,17633.000000,4.000000,27.000000,1,0,0,0,0
16,-1.000000,5.000000,3.000000,0.02,0.98,0,0.21,1.00,0.247,13.0,...,4.000000,27600.000000,9900.000000,3.000000,1.000000,0,0,0,0,1
17,-7.000000,-1.000000,-3.000000,0.02,0.98,300,0.60,0.43,0.355,19.0,...,10.000000,6600.000000,4062.000000,9.000000,7.000000,1,0,0,0,0
18,-24.000000,-71.000000,-20.000000,0.01,0.99,2000,0.87,1.00,0.377,15.0,...,4.000000,15600.000000,10275.000000,26.000000,77.000000,0,0,0,0,1
19,-10.000000,-31.000000,-6.000000,0.01,0.96,0,1.37,0.51,0.486,18.0,...,9.000000,20400.000000,8187.000000,12.000000,37.000000,1,0,0,0,0
20,-1.000000,-65.000000,3.000000,0.02,0.98,300,0.11,1.00,0.229,11.0,...,1.000000,8400.000000,8400.000000,3.000000,71.000000,1,0,0,0,0
21,-5.000000,-17.000000,-1.000000,0.02,0.98,0,0.43,0.66,0.369,15.0,...,3.000000,32400.000000,18600.000000,7.000000,23.000000,1,0,0,0,0
22,-5.000000,2.000000,-1.000000,0.00,0.59,0,3.48,0.92,0.255,19.0,...,11.000000,39600.000000,20454.000000,4.000000,1.000000,0,0,0,0,1
23,-10.000000,-3.000000,-6.000000,0.01,0.99,2400,1.71,0.57,0.388,18.0,...,7.000000,14400.000000,6100.000000,12.000000,9.000000,0,1,0,0,0
24,-12.000000,-98.000000,-8.000000,0.02,0.78,2500,1.90,0.83,0.336,23.0,...,3.000000,31200.000000,15500.000000,14.000000,104.000000,1,0,0,0,0
25,-22.000000,-79.000000,-18.000000,0.40,0.60,0,1.46,0.69,0.375,9.0,...,14.000000,42600.000000,9841.000000,21.000000,82.000000,0,0,0,0,1
26,-8.000000,-74.000000,-4.000000,0.02,0.96,0,12.35,0.96,0.444,20.0,...,2.000000,8100.000000,7050.000000,10.000000,80.000000,1,0,0,0,0
27,-18.000000,0.000000,-14.000000,0.01,0.91,2000,46.90,0.69,0.263,19.0,...,15.000000,13200.000000,6461.000000,20.000000,6.000000,0,1,0,0,0
28,-3.000000,-3.000000,1.000000,0.01,0.99,3000,0.91,0.93,0.305,21.0,...,1.000000,21600.000000,21600.000000,5.000000,9.000000,1,0,0,0,0
29,-22.789663,-28.000000,-18.789663,0.02,0.64,1500,1.02,0.44,0.211,15.0,...,1.000000,3000.000000,3000.000000,24.112809,34.000000,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4724,-19.000000,1.000000,-15.000000,0.02,0.98,1000,1.37,0.89,0.287,20.0,...,6.000000,9000.000000,3460.000000,21.000000,5.000000,1,0,0,0,0
4725,-140.000000,-94.000000,-136.000000,0.01,0.99,0,0.28,0.57,0.137,13.0,...,4.000000,21600.000000,11850.000000,142.000000,100.000000,1,0,0,0,0
4726,-20.000000,-50.000000,-16.000000,0.00,1.00,900,1.60,0.90,0.250,12.0,...,1.000000,4800.000000,4800.000000,19.000000,53.000000,0,0,0,0,1
4727,-26.000000,-51.000000,-22.000000,0.02,0.98,0,1.33,0.82,0.341,17.0,...,4.000000,12000.000000,5125.000000,28.000000,57.000000,1,0,0,0,0
4728,-16.000000,-3.000000,-12.000000,0.06,0.94,1500,4.70,1.00,0.444,16.0,...,6.000000,20400.000000,8933.000000,18.000000,9.000000,1,0,0,0,0
4729,-1.000000,-98.000000,3.000000,0.17,0.83,0,0.88,1.00,0.316,16.0,...,4.000000,16800.000000,7200.000000,3.000000,104.000000,1,0,0,0,0
4730,-26.000000,-122.000000,-22.000000,0.01,0.99,2000,0.54,0.44,0.215,17.0,...,1.000000,15600.000000,15600.000000,28.000000,128.000000,0,1,0,0,0
4731,0.000000,-5.000000,4.000000,0.00,0.58,2000,2.63,0.73,0.525,19.0,...,15.000000,124200.000000,25361.000000,2.000000,11.000000,0,1,0,0,0
4732,-7.000000,-244.000000,-3.000000,0.11,0.89,4000,49.37,1.00,0.115,12.0,...,2.000000,7200.000000,4950.000000,9.000000,250.000000,1,0,0,0,0
4733,-12.000000,-3.000000,-8.000000,0.03,0.97,1000,2.98,0.88,0.255,14.0,...,3.000000,13200.000000,6900.000000,14.000000,9.000000,0,0,1,0,0
4734,-22.000000,-125.000000,-18.000000,0.00,1.00,0,1.06,0.85,0.221,11.0,...,1.000000,1500.000000,1500.000000,24.000000,131.000000,0,0,0,0,1
4735,0.000000,0.000000,4.000000,0.01,0.61,5000,1.15,0.61,0.197,14.0,...,4.000000,34800.000000,21100.000000,2.000000,6.000000,1,0,0,0,0
4736,-16.000000,-150.000000,-12.000000,0.05,0.95,2000,2.39,1.00,0.207,12.0,...,1.000000,10200.000000,10200.000000,18.000000,156.000000,1,0,0,0,0
4737,-2.000000,-4.000000,2.000000,0.01,0.99,300,1.00,0.46,0.547,20.0,...,8.000000,20400.000000,11714.000000,1.000000,7.000000,1,0,0,0,0
4738,-46.000000,-83.000000,-42.000000,0.02,0.98,0,6.14,0.89,0.133,13.0,...,3.000000,7200.000000,5700.000000,48.000000,89.000000,1,0,0,0,0
4739,-13.000000,-6.000000,-9.000000,0.05,0.62,2400,0.28,0.67,0.403,17.0,...,3.000000,3900.000000,3600.000000,12.000000,9.000000,0,1,0,0,0
4740,-29.000000,-157.000000,-25.000000,0.07,0.93,9100,0.71,1.00,0.277,17.0,...,3.000000,12000.000000,9200.000000,31.000000,163.000000,1,0,0,0,0
4741,-10.000000,-137.000000,-6.000000,0.00,0.83,3000,0.54,1.00,0.441,20.0,...,3.000000,19800.000000,13900.000000,9.000000,140.000000,1,0,0,0,0
4742,-2.000000,2.000000,2.000000,0.02,0.98,11300,0.39,0.96,0.525,18.0,...,8.000000,21600.000000,7557.000000,4.000000,4.000000,1,0,0,0,0
4743,-12.000000,-9.000000,-8.000000,0.00,1.00,0,0.84,1.00,0.372,19.0,...,2.000000,3600.000000,2300.000000,11.000000,12.000000,0,1,0,0,0
4744,-3.000000,-82.000000,1.000000,0.01,0.96,0,0.89,0.45,0.405,15.0,...,11.000000,8400.000000,3344.000000,5.000000,88.000000,1,0,0,0,0
4745,1.000000,-2.000000,5.000000,0.04,0.96,400,0.79,0.67,0.348,15.0,...,4.000000,7200.000000,5850.000000,1.000000,8.000000,0,1,0,0,0
4746,-22.789663,-49.855957,-18.789663,0.01,0.91,1600,1.04,0.82,0.541,22.0,...,5.227507,16153.690823,8007.696881,24.112809,55.181512,1,0,0,0,0
4747,1.000000,-16.000000,5.000000,0.02,0.40,0,1.08,0.94,0.394,25.0,...,6.000000,6000.000000,3260.000000,1.000000,22.000000,0,0,0,0,1
4748,-33.000000,-48.000000,-29.000000,0.09,0.91,0,0.15,0.20,0.159,8.0,...,2.000000,19800.000000,18300.000000,35.000000,54.000000,1,0,0,0,0
4749,-42.000000,-52.000000,-38.000000,0.05,0.68,1000,0.87,0.94,0.150,16.0,...,1.000000,49200.000000,49200.000000,44.000000,58.000000,1,0,0,0,0
4750,-15.000000,-49.000000,-11.000000,0.01,0.99,400,0.93,0.98,0.605,18.0,...,8.000000,19200.000000,7500.000000,17.000000,55.000000,1,0,0,0,0
4751,-16.000000,-49.000000,-12.000000,0.00,1.00,3000,0.54,0.64,0.313,16.0,...,8.000000,21000.000000,7250.000000,18.000000,55.000000,1,0,0,0,0
4752,-56.000000,-13.000000,-52.000000,0.05,0.95,0,4.79,1.00,0.458,19.0,...,11.000000,12000.000000,3950.000000,55.000000,16.000000,1,0,0,0,0
4753,-18.000000,-48.000000,-14.000000,0.01,0.99,1300,21.35,1.00,0.372,22.0,...,5.000000,7800.000000,4360.000000,20.000000,54.000000,1,0,0,0,0

## 总结

在处理数据阶段
1. 看缺失值，根据缺失值占比排序，以及自己的需要，删除指定的前几个确实较多的特征。当然也可以不删除
2. 再排除掉特征的值都相同的列
3. 然后看数据类型，看如果存在非数值的，要处理这类，转换为数值型（注：时间类型可处理为时间序列）
4. 最后填充缺失的数据（注意填充确实数据的方法）